config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  resources :participants
  resources :events
  post '/events/:id/generate', to: 'events#generate'
  post '/qr_codes/:uuid/checkin', to: 'qr_codes#checkin'
  get '/participants/import', to: 'participants#import'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :participants

  resource :participants do
    post :import, on: :member
  end

end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :event
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  require 'csv'
  before_action :set_participant, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  def import
    file = params[:file]

    if file.nil?
      redirect_to '/participants', notice: 'No File Selected'
      return
    end
    event_id = params[:event]['event_id']

    if event_id.nil? || event_id == 0 || event_id == ''
      redirect_to '/participants', notice: 'Event not selected'
      return
    end

    CSV.foreach(file.path, headers: true) do |participant|
      participant_data = participant.to_hash
      participant_data['event_id'] = event_id
      Participant.create!(participant_data)
    end
    redirect_to '/participants', notice: 'Successfully imported participants'
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_participant
    @participant = Participant.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def participant_params
    params.require(:participant).permit(:name, :email, :contact_number, :from, :event_id)
  end

  def array_from_csv csv_file_name
    require 'csv'
    csv_file = File.read csv_file_name
    records = CSV.parse(csv_file, :headers => true)
    records .collect { |record| record }
  end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_for(participant) do |f| %>
  <% if participant.errors.any? %>
    <div id="error_explanation" class="top-margin-20 error">
      <div><%= pluralize(participant.errors.count, "error") %> prohibited this participant from being saved:</div>

      <ul>
      <% participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_area :name %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_area :email %>
  </div>

  <div class="form-group">
    <%= f.label :contact_number %>
    <%= f.text_field :contact_number %>
  </div>

  <div class="form-group">
    <%= f.label :from %>
    <%= f.text_area :from %>
  </div>

  <div class="form-group">
    <%= f.label :event_id %>
    <%= f.text_field :event_id %>
  </div>

  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<div class="container">
  <ul class="nav nav-tabs">
    <li><a href="/"> Events </a></li>
    <li class="active"><a href="/participants"> Participants </a></li>
  </ul>

  <div class="tab-content">
    <h1>Editing Participant</h1>

    <%= render 'form', participant: @participant %>

    <%= link_to 'Show', @participant %> |
    <%= link_to 'Back', participants_path %>
  </div>
</div>

app/views/participants/index.html.erb
<div class="container">
  <ul class="nav nav-tabs">
    <li><a href="/"> Events </a></li>
    <li class="active"><a href="/participants"> Participants </a></li>
  </ul>


  <div class="tab-content">
    <p id="notice" class="success top-margin-20"><%= notice %></p>

    <h1>Participants</h1>

    <table class="table table-striped">
      <thead>
      <tr>
        <th scope="row">Name</th>
        <th scope="row">Email</th>
        <th scope="row">Contact number</th>
        <th scope="row">From</th>
        <th scope="row">Event</th>
        <th colspan="3" scope="row"></th>
      </tr>
      </thead>

      <tbody>
      <% @participants.each do |participant| %>
          <tr>
            <td><%= participant.name %></td>
            <td><%= participant.email %></td>
            <td><%= participant.contact_number %></td>
            <td><%= participant.from %></td>
            <td><%= participant.event.name %></td>
            <td><%= link_to 'Show', participant %></td>
            <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
            <td><%= link_to 'Destroy', participant, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Participant', new_participant_path %>






    <h3> Import Participants</h3>
    <%= form_tag({:action => :import}, {multipart: true}) do %>
        <div class="form-group">
          <label>Select an event</label>
          <%= collection_select(:event, :event_id, Event.all, :id, :name_with_edition, prompt: true) %>
        </div>
        <div class="form-group">
          <label>Choose a file to upload participants</label>
          <%= file_field_tag :file, accept: 'text/csv' %>
        </div>
        <div class="form-group">
          <%= submit_tag "Import", :class => 'btn btn-primary' %>
        </div>
    <% end %>
  </div>
</div>

app/views/participants/new.html.erb
<div class="container">
  <ul class="nav nav-tabs">
    <li><a href="/"> Events </a></li>
    <li class="active"><a href="/participants"> Participants </a></li>
  </ul>

  <div class="tab-content">
    <h1>New Participant</h1>

    <%= render 'form', participant: @participant %>

    <%= link_to 'Back', participants_path %>
  </div>
</div>

app/views/participants/show.html.erb
<div class="container">
  <ul class="nav nav-tabs">
    <li><a href="/"> Events </a></li>
    <li class="active"><a href="/participants"> Participants </a></li>
  </ul>

  <div class="tab-content">
    <p id="notice" class="success top-margin-20"><%= notice %></p>

    <p>
      <strong>Name:</strong>
      <%= @participant.name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @participant.email %>
    </p>

    <p>
      <strong>Contact number:</strong>
      <%= @participant.contact_number %>
    </p>

    <p>
      <strong>From:</strong>
      <%= @participant.from %>
    </p>

    <p>
      <strong>Event:</strong>
      <%= @participant.event %>
    </p>

    <%= link_to 'Edit', edit_participant_path(@participant) %> |
    <%= link_to 'Back', participants_path %>
  </div>
</div>